### ISSUE TITLE
nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by dnowacki-usgs** [Doodleverse/dash_doodler#10]
Updated code to the latest release via `git pull`. Now when running `python appCRF.py` I get an error ending in `socket.gaierror: [Errno 8] nodename nor servname provided, or not known`. This is on macOS 10.14.6. Full traceback below:
```
(dashdoodler) dnowacki@IGSWAPWGWSM3114:~/projects/dash_doodler$ python appCRF.py
Results will be written to results/results2020-11-23-10-20-08
 * Serving Flask app "appCRF" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "appCRF.py", line 771, in <module>
    app.run_server() #debug=True, port=8888)
  File "/Users/dnowacki/miniconda3/envs/dashdoodler/lib/python3.6/site-packages/dash/dash.py", line 1574, in run_server
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/Users/dnowacki/miniconda3/envs/dashdoodler/lib/python3.6/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/Users/dnowacki/miniconda3/envs/dashdoodler/lib/python3.6/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/Users/dnowacki/miniconda3/envs/dashdoodler/lib/python3.6/site-packages/werkzeug/serving.py", line 1005, in inner
    fd=fd,
  File "/Users/dnowacki/miniconda3/envs/dashdoodler/lib/python3.6/site-packages/werkzeug/serving.py", line 848, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/Users/dnowacki/miniconda3/envs/dashdoodler/lib/python3.6/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/Users/dnowacki/miniconda3/envs/dashdoodler/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/Users/dnowacki/miniconda3/envs/dashdoodler/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Users/dnowacki/miniconda3/envs/dashdoodler/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Comment by ddbuscombe** [comment]
That's a strange one, thanks for reporting. Can you provide details of your OS, and network connection (VPN or no?) or any non-standard processes using your network? Does it make a difference if you use `debug=True`, or set a port manually? You could also specify the host manually, i.e. `host = '127.0.0.1'`

**Comment by ddbuscombe** [comment]
Sorry, I saw your OS details. Not able to troubleshot directly on a Mac, so let me know if any of those suggestions work

**Comment by ddbuscombe** [comment]
what do you see when you issue the following?

```
import socket
socket.gethostbyname(socket.gethostname())
```

**Comment by dnowacki-usgs** [comment]
Thanks Dan. Adding `host='127.0.0.1'` to the call to `app.run_server()` fixed the issue. 

As for the socket calls, I get the same error as the original post. I think the issue may be that `socket.gethostname()` replies with the GS-assigned hostname for my machine (`XXXXXX`), which doesn't have a corresponding entry in `/etc/hosts`. So the call to `socket.gethostbyname(...)` fails.

**Comment by ddbuscombe** [comment]
Awesome, thanks for the update. I'll add a note to the README
